[www]
user = www-data
group = www-data

listen = 9000

pm = static
pm.max_children = 20

pm.status_path = /status
ping.path = /ping

request_terminate_timeout = 60s

php_admin_value[error_log] = /var/log/fpm-php.www.log
php_admin_flag[log_errors] = on